### ISSUE TITLE
DLL Instantiation Challenges & GetToolTransform

### ISSUE THREAD

**Issue by adconk** [andreaskeller96/HoloLens2-IRTracking#2]
Hi @andreaskeller96, thanks tackling the first issue.  We realized we could add Tool definitions only before tracking start or after tracking stop, that was one of our hang ups with shutdown.  Once we figured that out, it worked well.  We would be quite interested in being able to add definitions while tracking is running. That would be very cool.

We haven't been able to get a tool transform with all zeros. Perhaps this Line should be an "==" instead of an "!="?
https://github.com/andreaskeller96/HoloLens2-IRTracking/blob/31a31068f92a65cb1efb333095b7cded54813e08/IRToolTrack.cpp#L28.  I could be way off, but we are unable to get a result of all zeros even when the IR array is covered up.  

Also, we've had success compiling OpenCV and the overall project, thanks to @denisshoth, but we're still having some challenges loading it into our Unity project.  It appears to fail silently.  Our winmd files are the same size (3kb), while our DLL files are very close (yours: 1,519 kb, ours: 1,523 kb).  Perhaps there's something small we are missing?

**Comment by andreaskeller96** [comment]
In theory the fact that the tracking can be restarted correctly now should mean that adding tool definitions while running is possible. Be aware though that the way this is currently implemented is by stopping tracking, changing the definitions and restarting it right after. I currently don’t have a HoloLens to test if this works correctly though.

In regards to the tool transform with all zeros: the current intended behavior is that you will only receive all zeros if the marker was never detected. Otherwise it will give the last known position and rotation. In addition, the last float in the tool transform array acts as a flag, with it being 1 if the tool was detected in the last analyzed frame, and 0 otherwise. This does not affect the returned transform though, and therefore must be handled in unity. A (better?) way of handling this would be to return the last timestamp when the marker was visible, but as of right now this would need to be tracked within unity.

What to do to make your custom compiled DLL work I can only speculate. My best guess is that Unity did not retain the correct settings for the library and winmd (it does not automatically determine that the library is for arm64 iirc). This can be changed in the properties of the files within unity asset browser.

**Comment by adconk** [comment]
hi @andreaskeller96 - you were exactly right with the DLL in Unity. It was the properties.  I got it working.  We'll try out the 0 / 1 flag from GetToolTransform and evaluate that. Thanks for the help!
